---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  namespace: crossplane-system
type: Opaque
data:
  creds: erererer

