---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: dev-main
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    region: us-east-1
    cidrBlock: 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    tags:
      Name: dev-main